### ISSUE TITLE
Build fails on CircleCI during checkout

### ISSUE THREAD

**Issue by sajjadtorabian** [BIDS-Apps/PyMVPA#3]
After migrating from Circle version 1 to 2, build fails on CircleCI during checkout:

Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
exit status 128

It seems like the BIDS-Apps/PyMVPA deploy key doesn't work any more, so I added a new user key which has temporarily solved the issue. However, I'm not sure if it should remain this way.

Chris, @effigies could you please look into this? Thanks so much!

**Comment by sajjadtorabian** [comment]
Also, although building is done successfully now (with the user key), I see build failing on the "Available BIDS Apps" webpage: https://bids-apps.neuroimaging.io/apps/

Not sure why this happens.

**Comment by effigies** [comment]
That takes a few minutes to update. It's passing now.

Thanks for pinging me. And also not waiting on me to respond. :-) It looks like you got this settled? Anything else need working through?

**Comment by sajjadtorabian** [comment]
The only thing I'm wondering about is why the deploy key doesn't work any more; and I manually added a user key through CircleCI to eventually be able to checkout my project. Attaching a screenshot of the page I'm looking at. If I remove "sajjadtorabian user key" the build will fail.

So, things are working, but I was wondering if we can get the deploy key to work again, and also didn't want the change from deploy to user key to maybe cause other issues. Thanks again for your time on checking this!

![Screenshot_2020-01-16_20-11-55](https://user-images.githubusercontent.com/15991358/72584257-385f9d80-389e-11ea-83f5-6b528689eea4.png)

**Comment by sajjadtorabian** [comment]
I'm closing this issue as the build is passing successfully, and new tests are being added as well. However, it would be great if you (Chris @effigies or Yaroslav @yarikoptic) could take another look into the issue with the deploy key. I'd appreciate it :)

Also, I think there is a problem with updates on this page: bids-apps.neuroimaging.io/apps/
The build for my app is never changing from failing to passing although it is successful on CircleCI, and also Image says not found which I think is because of the build. Thanks!

**Comment by effigies** [comment]
I stopped building and reenabled the repository. Your key no longer shows up, and a new deploy key appeared [here](https://github.com/BIDS-Apps/PyMVPA/settings/keys). Possibly there's a better way, but I don't know it.

**Comment by sajjadtorabian** [comment]
Thanks, the new deploy key is working! I just can't view [this](https://github.com/BIDS-Apps/PyMVPA/settings/keys) due to permissions, which doesn't matter.

Also, I don't know why the [BIDS Apps](https://bids-apps.neuroimaging.io/apps/) website doesn't update; not sure if the problem comes from my end.

**Comment by effigies** [comment]
What are you expecting to update on the website?

**Comment by sajjadtorabian** [comment]
In front of BIDS-Apps/PyMVPA, Image says "not found" and build says "failing" while everything is running successfully.

**Comment by effigies** [comment]
Resolved in ee92ed6822ec750a69fe8f369dfbed3b7710da04. Released [v2.0.2](https://github.com/BIDS-Apps/PyMVPA/releases/tag/v2.0.2). Seems to have updated now.

**Comment by yarikoptic** [comment]
Thank you @effigies !

**Comment by sajjadtorabian** [comment]
Thank you so much for your help with this, @effigies! The build is also passing now on the BIDS Apps website after a change from machine to docker executor under deployment, and adding setup_remote_docker
