### ISSUE TITLE
 Using PyMVPA BIDs app for multiple conditions at once 

### ISSUE THREAD

**Issue by sappelhoff** [BIDS-Apps/PyMVPA#5]
hey @sajjadtorabian --> this is just to make you aware of this issue: https://groups.google.com/forum/#!topic/bids-discussion/HT5HOIfjMfg

In case you hadn't seen it before.

**Comment by sajjadtorabian** [comment]
Thanks, @sappelhoff. I've replied to their question on bids-discussion. They simply need to use the conditions_to_classify argument with multiple condition labels.
