### ISSUE TITLE
Cannot open volume /bids_dataset/derivatives/fmriprep/sub-25/func/*exp*_preproc_bold

### ISSUE THREAD

**Issue by costantinoai** [BIDS-Apps/PyMVPA#8]
When building PyMVPA from docker, and running it on a BIDS (fmriprep) folder, I get the following error for all my subjects:

`docker run -i --rm -v D:\Andrea\fov\BIDS\derivatives\PyMVPA:/outputs bids/pymvpa /bids_dataset /outputs participant_prep -k exp --skip_bids_validator`

> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-02/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-03/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-04/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-05/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-06/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-07/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-08/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-09/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-10/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-11/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-12/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-13/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-14/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-15/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-16/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-17/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-18/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-19/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-20/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-21/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-22/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-23/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-24/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file
> Cannot open volume /bids_dataset/derivatives/fmriprep/sub-25/func/*exp*_preproc_bold for reading!
> ERROR: Could not open file

This is because run.py on line 123 is looking for a file called:

`"$out_path/$subj_name/""$subj_name""_task-""$task""_bold_space_preproc" $subjects/func/*$task*_preproc.nii.gz`

but the actual fmriprep file name would be:

`"$out_path/$subj_name/""$subj_name""_task-""$task""_bold_space_preproc" $subjects/func/*$task***-preproc_bold**.nii.gz`

**Comment by sajjadtorabian** [comment]
Please refer to the documentation for examples showing how to run in prep/test mode. You're only mounting your outputs folder and not the BIDS root directory. Here is how to do it:

`docker run -i --rm \
	-v [path to BIDS root]:/bids_dataset:ro \
	-v [path to BIDS root/derivatives/pymvpa]:/outputs \
	bids/pymvpa \
	/bids_dataset /outputs participant_prep -k objectviewing -p 1 2`
